inherit: true

tools:
    # Code Coverage
    external_code_coverage:
        enabled: true
        timeout: 600
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
