language: php
sudo: false

php:
  - 7.1
  - 7.2

os: linux

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction -vv $COMPOSER_FLAGS

script:
  - composer validate --strict
  - vendor/bin/phpunit -c phpunit.xml.dist --no-coverage --colors --verbose

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: vendor/bin/phpunit -c phpunit.xml.dist --colors --verbose --coverage-text --coverage-clover=coverage.clover
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover
    - stage: check coding style
      php: 7.1
      script: php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests/UserAgentsTest tests/BrowscapTest tests/fixtures
    - stage: integration test
      php: 7.1
      env:
        - TEST_SET="full"
      script: php -n vendor/bin/phpunit -c tests/phpunit-integration.xml.dist --no-coverage --colors --verbose tests/UserAgentsTest/FullTest.php
      after_success: bash <(curl -s https://codecov.io/bash) -f coverage-full.json -F full
    - stage: integration test
      php: 7.1
      env:
        - TEST_SET="standard"
      script: php -n vendor/bin/phpunit -c tests/phpunit-integration.xml.dist --no-coverage --colors --verbose tests/UserAgentsTest/StandardTest.php
      after_success: bash <(curl -s https://codecov.io/bash) -f coverage-standard.json -F standard
    - stage: integration test
      php: 7.1
      env:
        - TEST_SET="lite"
      script: php -n vendor/bin/phpunit -c tests/phpunit-integration.xml.dist --no-coverage --colors --verbose tests/UserAgentsTest/LiteTest.php
      after_success: bash <(curl -s https://codecov.io/bash) -f coverage-lite.json -F lite
