language: php
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - php: nightly

before_script:
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer install -o --prefer-source

script:
  - vendor/bin/phpunit --colors --verbose --exclude-group useragenttest --coverage-text --coverage-clover=coverage.clover
  - php -n vendor/bin/phpunit --no-coverage --colors --group useragenttest
  - php -n -d memory_limit=768M vendor/bin/phpcs --standard=psr2 -np src tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
