language: php
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != nightly && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv $COMPOSER_FLAGS

script:
  - composer validate --strict
  - vendor/bin/phpunit --exclude-group useragenttest --no-coverage --colors --exclude-group useragenttest

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      script: vendor/bin/phpunit --exclude-group useragenttest --colors --coverage-text --coverage-clover=coverage.clover
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script:
        - php -n -d memory_limit=768M vendor/bin/phpcs
    - stage: compare results
      php: 7.1
      env: COMPOSER_FLAGS=""
      script:
        - php -n vendor/bin/phpunit --no-coverage --colors --group useragenttest
      after_success:
        - bash <(curl -s https://codecov.io/bash)
