language: php
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - php: nightly

before_script:
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install -o --prefer-source

script:
  - if [ "`phpenv version-name`" == "7.0" ]; then vendor/bin/phpunit --colors --verbose --exclude-group useragenttest --coverage-text --coverage-clover=coverage.clover; fi
  - if [ "`phpenv version-name`" != "7.0" ]; then vendor/bin/phpunit --colors --verbose --exclude-group useragenttest; fi
  - vendor/bin/phpunit --no-coverage --colors --group useragenttest
  - vendor/bin/phpcs --standard=psr2 -np src tests

after_script:
  - if [ "`phpenv version-name`" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" == "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
